### ISSUE TITLE
opencv_createsamples not creating anything inside the 'samples' folder

### ISSUE THREAD

**Issue by ferranaltarriba** [mrnugget/opencv-haar-classifier-training#9]
Hi there!

when I run the command:

perl bin/createsamples.pl positives.txt negatives.txt samples 1500\
  "opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1\
  -maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 80 -h 40"

it doesn't create anything inside the 'samples' directory. I attach a screen capture showing it:
![captura de pantalla 2016-02-05 a les 12 39 02](https://cloud.githubusercontent.com/assets/5442526/12845345/79953472-cc05-11e5-8269-3970598054fc.png)

Am I doing something wrong?

Thanks a lot!! :)

**Comment by mrnugget** [comment]
Sorry, I don't see anything wrong with your command.

**Comment by anuragprasad95** [comment]
You are using 7 postive images.
So,you have to change that value in your code (i.e, 7 instead of 1500)

**Comment by harishpathak** [comment]
I have same issue...nothing is created in samples folder...I am on Mac

**Comment by rejaverion** [comment]
Hey I have the same issue. I'm on Windows. Only thing I changed is the w and h ratio, adjusted it to the right proportion with my images. I ran the command several times. Still no vec file shows up

**Comment by wei-han** [comment]
I was wondering if the number of samples in the step 5 should be the same as the number of positive images? I saw some people set the parameter different from the number of positive images.

**Comment by mrnugget** [comment]
> I was wondering if the number of samples in the step 5 should be the same as the number of positive images? I saw some people set the parameter different from the number of positive images.

See this resource for more information: http://note.sonots.com/SciSoftware/haartraining.html#e5c54f60

The author of `createsamples.pl` writes here:

> I also wrote a script, createtrainsamples.pl, to repeat the procedures 1000 (or some) times. I specified 7000 instead of 5000 as default because the Tutorial [1] states as "the reasonable number of positive samples is 7000." Please modify the path to createsamples and its option parameters directly written in the file.

The tutorial he's referencing is this one: http://note.sonots.com/SciSoftware/haartraining/document.html

**Comment by fazeelzama20** [comment]
@mrnugget i have changed the value from 7000 to 7 (as i have also used 7 positive images) in createsamples.pl, but then i didnt get the output. Anyone can help?

**Comment by developer239** [comment]
https://stackoverflow.com/questions/22504258/opencv-createsamples-has-no-error-but-no-samples-found

**Comment by johnd3v** [comment]
hi man is this fixed?

**Comment by developer239** [comment]
Basically, if you can't run the command then it has bad parameters. I found many different answers on the internet because I had this problem twice and in the end it was always because I made some mistake when setting the parameters:

- Make sure that `positives.txt` is not empty and its paths are correct
- Make sure that `negatives.txt` is not empty and its paths are correct

Also try change this value: -w 32 -h 32 (sweet spot is between 15 to 35)

```
perl bin/createsamples.pl positives.txt negatives.txt samples 3000 "opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 0  -maxyangle 0 maxzangle 0 -maxidev 40 -w 32 -h 32"
```

I hope this helps.

**Comment by johnd3v** [comment]
Still not working @developer239 no vec files created

**Comment by damiano1996** [comment]
I solved it changing the name of files, remove the spaces.

**Comment by bharatabhinav** [comment]
when I run the command:

perl bin/createsamples.pl positives.txt negatives.txt samples 1500
"opencv_createsamples -bgcolor 0 -bgthresh 0 -maxxangle 1.1
-maxyangle 1.1 maxzangle 0.5 -maxidev 40 -w 80 -h 40"

it doesn't create anything inside the 'samples' directory. still i m facing same issue .. Please help me 

I m running this command on REDHAT
Python version : 2.7 and opencv version :3.4.4
Thanks in Advance

**Comment by JizhouLiu-Daren** [comment]
Hey guys, 

I am wondering if I could help. I just met with this kind of problem while trying to use the createsamples function in opencv. 
My case is that when I tried to build opencv, the "createsamples" did not occur. So when I finally want to use it, it does not respond. What I did to fix it is to go back to the opencv source file I downloaded from Github. Go to .../opencv/apps/CMakeLists.txt . Surprisingly, I found in the last but 3-4 lines that the commands "ocv_add_app(traincascade);ocv_add_app(createsamples)" are commented. I deleted the "#" and rebuild the program by following this https://docs.opencv.org/2.4/doc/tutorials/introduction/linux_install/linux_install.html. Then I found it work.

**Comment by PrasadNR** [comment]
I don't have any spaces in my files. I have been trying with Cygwin on Windows and Ubuntu in VM. This used to work before. I am not sure what the issue is. I am using single channel grayscale images too. I am also avoiding setting unnecessary parameters like max angle for x, y, z and other parameters which are not needed. I am using 7404 positive samples and I tried that also (I clearly remember using some different number other than the number of positive samples and still getting it to work a year ago or so).

I have been stuck on this since hours and I don't know why this has been closed. I tried both 2.4.13 and 2.4.9 OpenCV versions.
